version: '3'
services:
  #publisher service
  producer:
    build: dockerize/
    volumes:
      - "$MINER/miner/maven-indexer:/dist"

    depends_on:
      - neo4j
      - rabbitmq
    command: dockerize -wait http://rabbitmq:15672 -timeout 30s /dist/run-producer.sh --queue rabbitmq:5672 $FILE_COMMAND

  #consumer service
  consumer:
    build: dockerize/
    volumes:
      - "$MINER/miner/maven-aether:/dist"
    depends_on:
      - neo4j
      - rabbitmq
    command: dockerize -wait http://neo4j:7474  -wait http://rabbitmq:15672/#/queues/%2F/artifactsQueue -timeout 60s /dist/run-consumer.sh --db neo4j:7687 --queue rabbitmq:5672

  #neo4j service
  neo4j:
    build: neo4j/
    volumes:
      - "$NEO4J_VAR/data:/data"
      #- "$NEO4J_VAR/logs:/logs"
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - neo4j.env
  #rabbit mq service
  rabbitmq:
    build: rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"
